version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo "Building application.."
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - '**/*'
