name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-west-1  

      - name: Trigger CodeBuild
        id: codebuild
        run: |
          build_id=$(aws codebuild start-build --project-name application-build --query 'build.id' --output text)
          echo "::set-output name=build_id::$build_id"

      - name: Wait for CodeBuild to complete
        run: |
          build_id="${{ steps.codebuild.outputs.build_id }}"
          echo "Build ID: $build_id"
          echo "Waiting for CodeBuild to complete..."
          
          build_status=$(aws codebuild batch-get-builds --ids $build_id --query 'builds[0].buildStatus' --output text)

          while [[ "$build_status" == "IN_PROGRESS" ]]; do
            echo "Build still in progress..."
            sleep 10
            build_status=$(aws codebuild batch-get-builds --ids $build_id --query 'builds[0].buildStatus' --output text)
          done

          if [[ "$build_status" != "SUCCEEDED" ]]; then
            echo "Build failed: $build_status"
            exit 1
          else
            echo "Build succeeded: $build_status"
          fi

      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name application \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name deployment-group \
            --s3-location bucket=my-build-artifacts-bucket,key=your-application-artifact.zip,bundleType=zip
